sudo: required

language: perl6

os:
  - linux
  - osx

env:
  global:
    - export PATH="/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs) main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get'
    packages:
      - rakudo-pkg

before_install:
  - echo $TRAVIS_OS_NAME
  # Debian-based libmagicwand-dev installation
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update                   ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagickwand-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                               ; fi
  # macOS rakudo-star and imagemagick installation
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install rakudo-star                  ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install imagemagick@7                ; fi

install:
  - zef install . && zef test . --verbose
