sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.01
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update                   ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagickwand-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                               ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install imagemagick                  ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then ls /usr/local/lib/                        ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then ls /usr/lib/                              ; fi
  - rakudobrew build panda
  - panda installdeps .

script: prove -v -e perl6 t/
